--TEST--
DB-4220 test blob with nul byte.
--FILE--
<?php 

require("testdb.inc");
global $db;  
open_db();

try {

  $data = "This is\000a test.";
  if (strlen($data) != 15) {
      echo "FAIL: test data does not contain a NULL";
      die;
  }
  $sql = "DROP TABLE DB_4220 CASCADE IF EXISTS";
  $db->query($sql);
  $sql = "CREATE TABLE DB_4220 (ID INT GENERATED BY DEFAULT AS IDENTITY, BLOB1 BLOB DEFAULT NULL,	PRIMARY KEY (ID))";
  $db->query($sql);

  $sql = "INSERT INTO DB_4220 (BLOB1) VALUES (:db_insert_placeholder_0)";
  $stmt = $db->prepare($sql);
  $stmt->bindParam(':db_insert_placeholder_0', $data, PDO::PARAM_LOB);
  $stmt->execute();
  $id = $db->lastInsertId();

  $sql = 'SELECT * FROM DB_4220 WHERE ID = :id';
  $stmt = $db->prepare($sql);
  $stmt->bindParam(':id', $id);
  $stmt->execute();
  $result = $stmt->fetchAll();
  if ($result[0]['BLOB1'] != $data) {
      echo "FAIL: compare\n";
  }
  //print_r($result);
  $db = NULL;
} catch(PDOException $e) {
  echo $e->getMessage();
}
$db = NULL;
echo "done\n";

?>
--EXPECT--
done