--TEST--
clob1 -- test clob with nul byte.
--FILE--
<?php 

require("testdb.inc");
global $db;  
open_db();

try {

  $data = "This is\000a test.";
  if (strlen($data) != 15) {
      echo "FAIL: test data does not contain a NULL";
      die;
  }
  $sql1 = "DROP TABLE CLOB1 CASCADE IF EXISTS";
  $db->query($sql1);
  $sql2 = "CREATE TABLE CLOB1 (ID INT GENERATED BY DEFAULT AS IDENTITY, CLOBFIELD CLOB NOT NULL DEFAULT '',	PRIMARY KEY (ID))";
  $db->query($sql2);

  $sql3 = "INSERT INTO CLOB1 (CLOBFIELD) VALUES (:db_insert_placeholder_0)";
  $stmt3 = $db->prepare($sql3);
  $stmt3->bindParam(':db_insert_placeholder_0', $data, PDO::PARAM_STR);
  $stmt3->execute();
  $id = $db->lastInsertId();

  $sql4 = 'SELECT * FROM CLOB1 WHERE ID = :id';
  $stmt4 = $db->prepare($sql4);
  $stmt4->bindParam(':id', $id);
  $stmt4->execute();
  $result = $stmt4->fetchAll();
  if ($result[0]['CLOBFIELD'] != $data) {
      echo "FAIL: compare\n";
  }
  //print_r($result);

  $data2 = '';
  $stmt3->bindParam(':db_insert_placeholder_0', $data2, PDO::PARAM_STR);
  $stmt3->execute();
  $id = $db->lastInsertId();
  print_r($id);
  

  $db = NULL;
} catch(PDOException $e) {
  echo $e->getMessage();
}
$db = NULL;
echo "\ndone\n";

?>
--EXPECT--
2
done