--TEST--
DB-3717 Drupal 7 testRegression_310447
--FILE--
<?php 

require("testdb.inc");
global $db;  
open_db();

try {  
  error_reporting(E_ALL);

  $sql = "drop table db_3717 if exists";
  $db->query($sql);

  $sql = "CREATE TABLE db_3717 ( id INT GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(255) NOT NULL DEFAULT '', age INT NOT NULL DEFAULT 0, job VARCHAR(255) NOT NULL DEFAULT 'Undefined', PRIMARY KEY (id), CONSTRAINT db_3717_name_key UNIQUE (name))";
  $db->query($sql);
  
  $sql = "CREATE INDEX db_3717_ages_idx ON db_3717 (age)";
  $db->query($sql);

  $sql = "INSERT INTO db_3717 (name, age, job) VALUES (?, ?, ?)";
  $stmt = $db->prepare($sql);
  $name = "Ringo";
  $age = "28";
  $job = "Dummer";
  $stmt->bindParam(1, $name, PDO::PARAM_STR);
  $stmt->bindParam(2, $age, PDO::PARAM_STR);
  $stmt->bindParam(3, $job, PDO::PARAM_STR);
  $stmt->execute();

  $name = "Paul";
  $age = "26";
  $job = "Bass";
  $stmt->bindParam(1, $name, PDO::PARAM_STR);
  $stmt->bindParam(2, $age, PDO::PARAM_STR);
  $stmt->bindParam(3, $job, PDO::PARAM_STR);
  $stmt->execute();

  $utf8name = str_repeat("é", 255);
  $age = "20";
  $job = "Dancer";
  $stmt->bindParam(1, $utf8name, PDO::PARAM_STR);
  $stmt->bindParam(2, $age, PDO::PARAM_STR);
  $stmt->bindParam(3, $job, PDO::PARAM_STR);
  $stmt->execute();

  $sql = "SELECT name FROM db_3717 WHERE name = :name";
  $stmt = $db->prepare($sql);
  $stmt->bindParam(":name", $utf8name, PDO::PARAM_STR);
  $stmt->execute();
  $result = $stmt->fetchAll();
  foreach ($result as $row) {
     print_r ($row);
  }

  $db = NULL;

} catch(PDOException $e) {  
  echo $e->getMessage();  
}
$db = NULL;
echo "done\n";
?>
--EXPECT--
Array
(
    [A] => 36.9500
    [0] => 36.9500
)
done