--TEST--
DB-4594	
--FILE--
<?php 
date_default_timezone_set('America/New_York');

require("testdb.inc");
global $db;  
open_db();

try {  
  $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

  $sql0 = 'DROP TABLE "simpletest101596locales_source" CASCADE IF EXISTS';
  $db->query($sql0);

  $sql0 = 'DROP TABLE "simpletest101596locales_target" CASCADE IF EXISTS';
  $db->query($sql0);

  $sql1 = 'CREATE TABLE "simpletest101596locales_source" (
	"lid" INT GENERATED BY DEFAULT AS IDENTITY,
	"location" TEXT NULL DEFAULT NULL,
	"textgroup" VARCHAR(255) NOT NULL DEFAULT \'default\',
	"source" TEXT NOT NULL,
	"context" VARCHAR(255) NOT NULL DEFAULT \'\',
	"version" VARCHAR(20) NOT NULL DEFAULT \'none\',
	PRIMARY KEY (lid)
	)';
  $db->query($sql1);

  $sql2 = 'CREATE TABLE "simpletest101596locales_target" (
	"lid" INT NOT NULL DEFAULT 0,
	"translation" TEXT NOT NULL,
	"language" VARCHAR(12) NOT NULL DEFAULT \'\',
	"plid" INT NOT NULL DEFAULT 0,
	"plural" INT NOT NULL DEFAULT 0,
	PRIMARY KEY (language, lid, plural)
	)';
  $db->query($sql2);

  $sql3 = "SELECT COUNT(*) AS expression
FROM 
( SELECT 1 AS expression
FROM 
simpletest101596locales_source s
LEFT OUTER JOIN simpletest101596locales_target t ON t.lid = s.lid
 WHERE ( (s.source LIKE :db_condition_placeholder_0 ESCAPE '\') OR (t.translation LIKE :db_condition_placeholder_1 ESCAPE '\') ) ) subquery";

  $stmt3 = $db->prepare($sql3);
  if (!$stmt3) {
    echo "\nPDO::errorInfo():\n";
    print_r($db->errorInfo());
  }
  $param0 = "%%";
  $param1 = "%%";
  $status = $stmt3->bindParam(':db_condition_placeholder_0', $param0, PDO::PARAM_STR);
  if (!$status) {
    echo "\nPDO::errorInfo():\n";
    print_r($stmt3->errorInfo());
  }
  $status = $stmt3->bindParam(':db_condition_placeholder_1', $param1, PDO::PARAM_STR);
  if (!$status) {
    echo "\nPDO::errorInfo():\n";
    print_r($stmt3->errorInfo());
  }
  $stmt3->execute();

  $db = NULL;
} catch(PDOException $e) {  
  echo $e->getMessage();  
}
$db = NULL;  
echo "\ndone\n";
?>
--EXPECT--
PDO::errorInfo():
Array
(
    [0] => 42P02
    [1] => -12
    [2] => Invalid parameter name ':db_condition_placeholder_1'
)

done