--TEST--
sequences test
--FILE--
<?php 
date_default_timezone_set('America/New_York');

require("testdb.inc");
global $db;  
open_db();

function nextId($existing_id = 0) {
  global $db;
  $sql1 = 'SELECT value FROM sequences';
  echo "sql1: " . $sql1 . "\n";
  $stmt1 = $db->prepare($sql1);
  $stmt1->execute();
  $new_id = $stmt1->fetchColumn(0);
  if (!$new_id) {
    $existing_id++;
    $sql2 = 'INSERT INTO sequences (value) VALUES (:existing_id)';
    echo "sql2: " . $sql2 . "\n";
    $stmt2 = $db->prepare($sql2);
    $stmt2->bindParam(':existing_id', $existing_id, PDO::PARAM_STR);
    $stmt2->execute();

    $sql3 = 'SELECT value FROM sequences';
    echo "sql3: " . $sql3 . "\n";
    $stmt3 = $db->prepare($sql3);
    $r3 = $stmt3->execute();
    return $stmt3->fetchColumn(0);
  }
  if ($existing_id > $new_id) {
      $new_id = $existing_id;
  }
  $new_id += 1;
  $sql4 = 'UPDATE sequences SET value = :new_id';
  echo "sql4: " . $sql4 . "\n";
  $stmt4 = $db->prepare($sql4);
  $stmt4->bindParam(':new_id', $new_id, PDO::PARAM_STR);
  $stmt4->execute();
  return $new_id; 
}


function test1() {
  global $db;
  $sql10 = 'DROP TABLE "sequences" CASCADE IF EXISTS';
  echo "sql10: " . $sql10 . "\n";
  $db->query($sql10);

  $sql11 = 'CREATE TABLE "sequences" (
	"value" INT GENERATED BY DEFAULT AS IDENTITY,
	PRIMARY KEY (value)
	)';
  echo "sql11: " . $sql11 . "\n";
  $db->query($sql11);

  nextId();
  nextId();

  $sql12 = 'SELECT MAX(value) FROM sequences';
  echo "sql12: " . $sql12 . "\n";
  $stmt12 = $db->prepare($sql12);
  $stmt12->execute();
  $value12 = $stmt12->fetchColumn(0);
  var_dump($value12);

  $sql13 = 'SELECT COUNT(*) FROM sequences';
  echo "sql13: " . $sql13 . "\n";
  $stmt13 = $db->prepare($sql13);
  $stmt13->execute();
  $value13 = $stmt13->fetchColumn(0);
  var_dump($value13);

}


try {  
  $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

  echo "\nPDO::ATTR_STRINGIFY_FETCHES=FALSE\n";
  $db->setAttribute(PDO::ATTR_STRINGIFY_FETCHES, FALSE);
  test1();

  echo "\nPDO::ATTR_STRINGIFY_FETCHES=TRUE\n";
  $db->setAttribute(PDO::ATTR_STRINGIFY_FETCHES, TRUE);
  test1();

  $db = NULL;
} catch(PDOException $e) {  
  echo $e->getMessage();  
}
$db = NULL;  
echo "\ndone\n";
?>
--EXPECT--
PDO::ATTR_STRINGIFY_FETCHES=FALSE
sql10: DROP TABLE "sequences" CASCADE IF EXISTS
sql11: CREATE TABLE "sequences" (
	"value" INT GENERATED BY DEFAULT AS IDENTITY,
	PRIMARY KEY (value)
	)
sql1: SELECT value FROM sequences
sql2: INSERT INTO sequences (value) VALUES (:existing_id)
sql3: SELECT value FROM sequences
sql1: SELECT value FROM sequences
sql4: UPDATE sequences SET value = :new_id
sql12: SELECT MAX(value) FROM sequences
int(2)
sql13: SELECT COUNT(*) FROM sequences
int(1)

PDO::ATTR_STRINGIFY_FETCHES=TRUE
sql10: DROP TABLE "sequences" CASCADE IF EXISTS
sql11: CREATE TABLE "sequences" (
	"value" INT GENERATED BY DEFAULT AS IDENTITY,
	PRIMARY KEY (value)
	)
sql1: SELECT value FROM sequences
sql2: INSERT INTO sequences (value) VALUES (:existing_id)
sql3: SELECT value FROM sequences
sql1: SELECT value FROM sequences
sql4: UPDATE sequences SET value = :new_id
sql12: SELECT MAX(value) FROM sequences
string(1) "2"
sql13: SELECT COUNT(*) FROM sequences
string(1) "1"

done
